// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txilzcdwvcmhgejwxnrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aWx6Y2R3dmNtaGdland4bnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjMyMzQsImV4cCI6MjA2NTg5OTIzNH0.ZtjJdblQBokG_vfkR_yfycKWQc01yJIp9LYseTM8VTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);